# Generated by Django 4.2.6 on 2024-01-20 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('village', '0003_village_max_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_stay_day', models.PositiveIntegerField(blank=True)),
                ('num_of_guests', models.PositiveIntegerField(blank=True)),
                ('reservator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='village.village')),
            ],
        ),
    ]
