# Generated by Django 4.2.6 on 2024-01-09 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tireng/media/village_img')),
                ('address', models.CharField(max_length=200)),
                ('num_of_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('meterage', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_day', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
