# Generated by Django 4.2.6 on 2024-01-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_alter_village_description_alter_village_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='max_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
