# Generated by Django 4.2.6 on 2024-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_village_max_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
