version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - tireng_network
    depends_on:
      - tireng_pg

  tireng_pg:
    image: postgres
    container_name: tireng_pg
    env_file:
      - env/.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - tireng_network

volumes:
  postgres_data:
networks:
  tireng_network: